### ISSUE TITLE
Refactoring of mac_frag_get_fragment

### ISSUE THREAD

**Issue by dl1com** [HAMNET-Access-Protocol/HNAP4PlutoSDR#42]
Currently (5ffd0417ecce7a9df6af43c2844005a180fcd570), `mac_frag_get_fragment` has over 100 lines and deep intendation nesting.
Refactoring is desirable.

**Comment by lukasostendorf** [comment]
I've started this by changing some if statements and splitting the functionality into some sub-functions: https://github.com/HAMNET-Access-Protocol/HNAP4PlutoSDR/pull/37/commits/acb6b483a44d6415d724c5b1047a540adc9c927f
