### ISSUE TITLE
Remove .zip ending for Github artifacts

### ISSUE THREAD

**Issue by dl1com** [HAMNET-Access-Protocol/HNAP4PlutoSDR#44]
Currently, we put a ".zip" file extension to our Github artifacts. But as Github is doing this automatically on its own anyway, we currently end up with ".zip.zip" for the artifcats.

Remove ".zip" in 
* https://github.com/HAMNET-Access-Protocol/HNAP4PlutoSDR/blob/develop/.github/workflows/build.yml#L83
* https://github.com/HAMNET-Access-Protocol/HNAP4PlutoSDR/blob/develop/.github/workflows/build.yml#L116
and
* https://github.com/HAMNET-Access-Protocol/HNAP4PlutoSDR/blob/develop/.github/workflows/build.yml#L152

//cc @dg8ngn

**Comment by AshwinKul28** [comment]
Hello, I would like to take this up :) Can you please assign it to me?

**Comment by dl1com** [comment]
> Hello, I would like to take this up :) Can you please assign it to me?

Thanks, but as this was a very small change, I just fixed it in the online editor.
