### ISSUE TITLE
Set up LLDP daemon

### ISSUE THREAD

**Issue by chris007de** [HAMNET-Access-Protocol/HNAP4PlutoSDR#5]
Proposal: encode callsign in TAP device MAC address

**Comment by dg8ngn** [comment]
Use LLDP to display:
- Callsign
- Platform
- Software Version

Suggestion:
configure system platform "plutosdr-fw <tag>"     <- tag = v0.32 (tag information may be stored somewhere in local file system?)
configure system description "<callsign> <software version>"     <- software version = commit-hash?

**Comment by dg8ngn** [comment]
Use LLDP to display:
- Callsign
- Platform
- Software Version

Suggestion:
configure system platform "plutosdr-fw <tag>"     <- tag = v0.32 (tag information may be stored somewhere in local file system?)
configure system description "<callsign> <software version>"     <- software version = commit-hash?
